-- ============================================================================
-- 🔓 EMERGENCY SUBSCRIPTION FIX
-- ============================================================================
-- Run this script in the Supabase SQL Editor to instantly activate 
-- subscriptions for all clinics.
-- ============================================================================

-- 1. Update existing subscriptions to be ACTIVE and valid for 10 years
UPDATE public.clinic_subscriptions
SET 
    status = 'active',
    end_date = (CURRENT_DATE + INTERVAL '10 years')::date,
    trial_end_date = NULL,
    updated_at = NOW(),
    notes = 'Emergency activation via FIX_SUBSCRIPTION_EXPIRY.sql'
WHERE 
    status IN ('expired', 'trial', 'suspended', 'cancelled')
    OR end_date < CURRENT_DATE;

-- 2. Insert subscription for any doctor that doesn't have one
INSERT INTO public.clinic_subscriptions (
    clinic_id,
    plan_id,
    status,
    start_date,
    end_date,
    notes
)
SELECT 
    d.id,
    (SELECT id FROM public.subscription_plans WHERE name = 'enterprise' LIMIT 1),
    'active',
    CURRENT_DATE,
    (CURRENT_DATE + INTERVAL '10 years')::date,
    'Auto-generated by FIX_SUBSCRIPTION_EXPIRY.sql'
FROM public.doctors d
WHERE d.user_role = 'doctor'
    AND NOT EXISTS (
        SELECT 1 FROM public.clinic_subscriptions cs WHERE cs.clinic_id = d.id
    );

-- 3. Verify the Fix
SELECT 
    d.name as clinic_name,
    cs.status,
    cs.end_date,
    sp.display_name as plan
FROM public.clinic_subscriptions cs
JOIN public.doctors d ON d.id = cs.clinic_id
JOIN public.subscription_plans sp ON sp.id = cs.plan_id;
